### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_kernel_driver_active'

### ISSUE THREAD

**Issue by diegopolido** [rodgomesc/avell-unofficial-control-center#20]
### WHY

Running `aucc -c green -b 4`, I got:

```
Traceback (most recent call last):
  File "/usr/local/bin/aucc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/aucc/main.py", line 86, in main
    control = ControlCenter(vendor_id=0x048d, product_id=0xce00)
  File "/usr/local/lib/python3.5/dist-packages/aucc/main.py", line 37, in __init__
    super(ControlCenter, self).__init__(vendor_id, product_id)
  File "/usr/local/lib/python3.5/dist-packages/aucc/core/handler.py", line 50, in __init__
    super(DeviceHandler, self).__init__(vendor_id, product_id)
  File "/usr/local/lib/python3.5/dist-packages/aucc/core/handler.py", line 16, in __init__
    self._device = self._get_device(vendor_id, product_id)
  File "/usr/local/lib/python3.5/dist-packages/aucc/core/handler.py", line 27, in _get_device
    if device.is_kernel_driver_active(1):
AttributeError: 'NoneType' object has no attribute 'is_kernel_driver_active'
```

**Comment by rodgomesc** [comment]
Check README instructions to see If your Device is compattible , you must have specific ITE.8291 REV0.03, to run this project
