### ISSUE TITLE
Ubuntu 20.04 on XMG Neo 15

### ISSUE THREAD

**Issue by Davidsastresas** [rodgomesc/avell-unofficial-control-center#69]
Hello,

On the setup listed above, I can not get this project to run. the keyboard seems to be: 

keyboard:
                       Integrated Technology Express ITE Device(8291)
                       Logitech USB Receiver
  /dev/input/event11   Holtek USB Gaming Keyboard
  /dev/input/event3    AT Translated Set 2 keyboard

and when running any aucc command this is the output:

sudo Traceback (most recent call last):
  File "/usr/local/bin/aucc", line 11, in <module>
    load_entry_point('avell-unofficial-control-center==1.0.4', 'console_scripts', 'aucc')()
  File "/usr/local/lib/python3.8/dist-packages/avell_unofficial_control_center-1.0.4-py3.8.egg/aucc/main.py", line 165, in main
  File "/usr/local/lib/python3.8/dist-packages/avell_unofficial_control_center-1.0.4-py3.8.egg/aucc/main.py", line 104, in __init__
  File "/usr/local/lib/python3.8/dist-packages/avell_unofficial_control_center-1.0.4-py3.8.egg/aucc/core/handler.py", line 50, in __init__
  File "/usr/local/lib/python3.8/dist-packages/avell_unofficial_control_center-1.0.4-py3.8.egg/aucc/core/handler.py", line 16, in __init__
  File "/usr/local/lib/python3.8/dist-packages/avell_unofficial_control_center-1.0.4-py3.8.egg/aucc/core/handler.py", line 27, in _get_device
AttributeError: 'NoneType' object has no attribute 'is_kernel_driver_active'

I am on kernel 5.17, it was needed to make the nvidia GPU work on this computer, not sure if that is important though...

Any suggestions? thank you very much!

**Comment by maik-dmxc** [comment]
same on 22.04
Kernel 5.15.0-46

`maik@maik-XMG-CORE-REN-E21:~$ aucc -c green -b 4
Traceback (most recent call last):
  File "/usr/local/bin/aucc", line 33, in <module>
    sys.exit(load_entry_point('avell-unofficial-control-center==1.0.4', 'console_scripts', 'aucc')())
  File "/usr/local/lib/python3.10/dist-packages/avell_unofficial_control_center-1.0.4-py3.10.egg/aucc/main.py", line 165, in main
  File "/usr/local/lib/python3.10/dist-packages/avell_unofficial_control_center-1.0.4-py3.10.egg/aucc/main.py", line 104, in __init__
  File "/usr/local/lib/python3.10/dist-packages/avell_unofficial_control_center-1.0.4-py3.10.egg/aucc/core/handler.py", line 50, in __init__
  File "/usr/local/lib/python3.10/dist-packages/avell_unofficial_control_center-1.0.4-py3.10.egg/aucc/core/handler.py", line 16, in __init__
  File "/usr/local/lib/python3.10/dist-packages/avell_unofficial_control_center-1.0.4-py3.10.egg/aucc/core/handler.py", line 27, in _get_device
AttributeError: 'NoneType' object has no attribute 'is_kernel_driver_active'
maik@maik-XMG-CORE-REN-E21:~$ `

regards maik
