### ISSUE TITLE
Avell A70 unsupported?

### ISSUE THREAD

**Issue by AxeLanderMoreira** [rodgomesc/avell-unofficial-control-center#71]
`sudo hwinfo --short` lists my device as:

keyboard:
  /dev/input/event3    AT Translated Set 2 keyboard

When I run `aucc -d`, I get an error:

Traceback (most recent call last):
  File "/usr/local/bin/aucc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/aucc/main.py", line 86, in main
    control = ControlCenter(vendor_id=0x048d, product_id=0xce00)
  File "/usr/local/lib/python3.8/dist-packages/aucc/main.py", line 37, in __init__
    super(ControlCenter, self).__init__(vendor_id, product_id)
  File "/usr/local/lib/python3.8/dist-packages/aucc/core/handler.py", line 50, in __init__
    super(DeviceHandler, self).__init__(vendor_id, product_id)
  File "/usr/local/lib/python3.8/dist-packages/aucc/core/handler.py", line 16, in __init__
    self._device = self._get_device(vendor_id, product_id)
  File "/usr/local/lib/python3.8/dist-packages/aucc/core/handler.py", line 27, in _get_device
    if device.is_kernel_driver_active(1):
AttributeError: 'NoneType' object has no attribute 'is_kernel_driver_active'

**Comment by jariojose** [comment]
Did you find a solution?

**Comment by AxeLanderMoreira** [comment]
Hi @jariojose . Unfortunately not.

At least the Fn+F6 combination works for me, and I can dim down and turn off the lights. But no way to make the control-center actually work.

**Comment by madebyluque** [comment]
Also an A70 user, and it is also not working here with the same error @AxeLanderMoreira mentioned.

**Comment by weldyss** [comment]
Hey guys. I made a small change on tuxedo-drivers to have it working on my A70. I tested this on fedora 43 with kernel 6.19.13. It's very specific to my case, but evertyhing is running well. https://github.com/weldyss/tuxedo-drivers. I also put in there some instructions to change the color and intensity (it's for me to not feel lost when need to change it)
