### ISSUE TITLE
Cannot run after update to Python on Manjaro

### ISSUE THREAD

**Issue by ryanrapini** [rodgomesc/avell-unofficial-control-center#73]
**Python 3.11.3**
**local/python-avell-unofficial-control-center-git 1.0.4.r62.e32e243-2**

I have verified I have **python-importlib-metadata 5.0.0-5** installed

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aucc", line 33, in <module>
    sys.exit(load_entry_point('avell-unofficial-control-center==1.0.4', 'console_scripts', 'aucc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/aucc", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for avell-unofficial-control-center

```

let me know if you need any additional information.

**Comment by ryanrapini** [comment]
Solved the issue by:

```
python3 -m pip install --upgrade pip setuptools wheel  
```

Remove and reinstall the package

```
pip3 install elevate
```

Can't say exactly what fixed it.
